"""add antibody project foundation

Revision ID: 0002_antibody_projects
Revises: 0001_legacy_schema
Create Date: 2026-09-16 19:06:33.153959
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0002_antibody_projects'
down_revision: Union[str, None] = '0001_legacy_schema'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('antibody_projects',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('owner_id', sa.String(length=36), nullable=False),
    sa.Column('project_code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('target_name', sa.String(length=160), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('owner_id', 'project_code', name='uq_antibody_projects_owner_code')
    )
    op.create_index(op.f('ix_antibody_projects_owner_id'), 'antibody_projects', ['owner_id'], unique=False)
    op.create_index('ix_antibody_projects_owner_status', 'antibody_projects', ['owner_id', 'status'], unique=False)
    op.create_index(op.f('ix_antibody_projects_status'), 'antibody_projects', ['status'], unique=False)
    op.create_index(op.f('ix_antibody_projects_target_name'), 'antibody_projects', ['target_name'], unique=False)
    op.create_table('antibody_audit_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('entity_type', sa.String(length=32), nullable=False),
    sa.Column('entity_id', sa.String(length=36), nullable=False),
    sa.Column('action', sa.String(length=32), nullable=False),
    sa.Column('actor_id', sa.String(length=36), nullable=True),
    sa.Column('before_json', sa.JSON(), nullable=True),
    sa.Column('after_json', sa.JSON(), nullable=True),
    sa.Column('request_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['antibody_projects.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_antibody_audit_entity', 'antibody_audit_events', ['entity_type', 'entity_id'], unique=False)
    op.create_index(op.f('ix_antibody_audit_events_project_id'), 'antibody_audit_events', ['project_id'], unique=False)
    op.create_index(op.f('ix_antibody_audit_events_request_id'), 'antibody_audit_events', ['request_id'], unique=False)
    op.create_index('ix_antibody_audit_project_created', 'antibody_audit_events', ['project_id', 'created_at'], unique=False)
    op.create_table('antibody_candidates',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('candidate_code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('antibody_type', sa.String(length=16), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['project_id'], ['antibody_projects.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'candidate_code', name='uq_antibody_candidate_code')
    )
    op.create_index(op.f('ix_antibody_candidates_project_id'), 'antibody_candidates', ['project_id'], unique=False)
    op.create_index('ix_antibody_candidates_project_status', 'antibody_candidates', ['project_id', 'status'], unique=False)
    op.create_index(op.f('ix_antibody_candidates_status'), 'antibody_candidates', ['status'], unique=False)
    op.create_table('antibody_project_members',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['antibody_projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'user_id', name='uq_antibody_project_member')
    )
    op.create_index(op.f('ix_antibody_project_members_project_id'), 'antibody_project_members', ['project_id'], unique=False)
    op.create_index(op.f('ix_antibody_project_members_user_id'), 'antibody_project_members', ['user_id'], unique=False)
    op.create_table('antibody_versions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('candidate_id', sa.String(length=36), nullable=False),
    sa.Column('primary_parent_id', sa.String(length=36), nullable=True),
    sa.Column('version_code', sa.String(length=32), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('purpose', sa.Text(), nullable=True),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('evidence', sa.Text(), nullable=True),
    sa.Column('sequence_hash', sa.String(length=64), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('locked_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('primary_parent_id IS NULL OR primary_parent_id <> id', name='ck_antibody_version_not_own_parent'),
    sa.CheckConstraint('version_number >= 0', name='ck_antibody_version_number_positive'),
    sa.ForeignKeyConstraint(['candidate_id'], ['antibody_candidates.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['primary_parent_id'], ['antibody_versions.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('candidate_id', 'version_code', name='uq_antibody_version_code'),
    sa.UniqueConstraint('candidate_id', 'version_number', name='uq_antibody_version_number')
    )
    op.create_index(op.f('ix_antibody_versions_candidate_id'), 'antibody_versions', ['candidate_id'], unique=False)
    op.create_index('ix_antibody_versions_candidate_status', 'antibody_versions', ['candidate_id', 'status'], unique=False)
    op.create_index(op.f('ix_antibody_versions_sequence_hash'), 'antibody_versions', ['sequence_hash'], unique=False)
    op.create_index(op.f('ix_antibody_versions_status'), 'antibody_versions', ['status'], unique=False)
    op.create_table('antibody_project_job_links',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('version_id', sa.String(length=36), nullable=False),
    sa.Column('job_id', sa.String(length=36), nullable=True),
    sa.Column('original_job_id', sa.String(length=36), nullable=False),
    sa.Column('engine', sa.String(length=32), nullable=False),
    sa.Column('purpose', sa.String(length=160), nullable=True),
    sa.Column('input_sequence_hash', sa.String(length=64), nullable=False),
    sa.Column('params_snapshot', sa.JSON(), nullable=True),
    sa.Column('result_snapshot', sa.JSON(), nullable=True),
    sa.Column('linked_by', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['linked_by'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['project_id'], ['antibody_projects.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['version_id'], ['antibody_versions.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('version_id', 'original_job_id', name='uq_antibody_version_original_job')
    )
    op.create_index(op.f('ix_antibody_project_job_links_job_id'), 'antibody_project_job_links', ['job_id'], unique=False)
    op.create_index(op.f('ix_antibody_project_job_links_project_id'), 'antibody_project_job_links', ['project_id'], unique=False)
    op.create_index(op.f('ix_antibody_project_job_links_version_id'), 'antibody_project_job_links', ['version_id'], unique=False)
    op.create_table('antibody_sample_batches',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('version_id', sa.String(length=36), nullable=False),
    sa.Column('batch_code', sa.String(length=64), nullable=False),
    sa.Column('expression_date', sa.Date(), nullable=True),
    sa.Column('purification_date', sa.Date(), nullable=True),
    sa.Column('concentration_value', sa.Float(), nullable=True),
    sa.Column('concentration_unit', sa.String(length=24), nullable=True),
    sa.Column('purity_percent', sa.Float(), nullable=True),
    sa.Column('storage_location', sa.String(length=255), nullable=True),
    sa.Column('operator_id', sa.String(length=36), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['operator_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['version_id'], ['antibody_versions.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('version_id', 'batch_code', name='uq_antibody_sample_batch_code')
    )
    op.create_index(op.f('ix_antibody_sample_batches_version_id'), 'antibody_sample_batches', ['version_id'], unique=False)
    op.create_table('antibody_version_chains',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('version_id', sa.String(length=36), nullable=False),
    sa.Column('chain_role', sa.String(length=16), nullable=False),
    sa.Column('chain_name', sa.String(length=64), nullable=True),
    sa.Column('variable_sequence', sa.Text(), nullable=False),
    sa.Column('full_sequence', sa.Text(), nullable=True),
    sa.Column('sequence_hash', sa.String(length=64), nullable=False),
    sa.Column('numbering_scheme', sa.String(length=16), nullable=False),
    sa.Column('annotation_json', sa.JSON(), nullable=True),
    sa.Column('annotation_tool', sa.String(length=64), nullable=True),
    sa.Column('annotation_version', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['version_id'], ['antibody_versions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('version_id', 'chain_role', name='uq_antibody_version_chain_role')
    )
    op.create_index(op.f('ix_antibody_version_chains_sequence_hash'), 'antibody_version_chains', ['sequence_hash'], unique=False)
    op.create_index(op.f('ix_antibody_version_chains_version_id'), 'antibody_version_chains', ['version_id'], unique=False)
    op.create_table('antibody_version_mutations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('version_id', sa.String(length=36), nullable=False),
    sa.Column('parent_version_id', sa.String(length=36), nullable=False),
    sa.Column('chain_role', sa.String(length=16), nullable=False),
    sa.Column('mutation_type', sa.String(length=16), nullable=False),
    sa.Column('sequence_position', sa.Integer(), nullable=True),
    sa.Column('numbering_label', sa.String(length=24), nullable=True),
    sa.Column('kabat_label', sa.String(length=24), nullable=True),
    sa.Column('from_aa', sa.String(length=8), nullable=True),
    sa.Column('to_aa', sa.String(length=8), nullable=True),
    sa.Column('region', sa.String(length=24), nullable=True),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('expected_effect', sa.Text(), nullable=True),
    sa.Column('evidence', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['parent_version_id'], ['antibody_versions.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['version_id'], ['antibody_versions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_antibody_mutations_version_chain', 'antibody_version_mutations', ['version_id', 'chain_role'], unique=False)
    op.create_index(op.f('ix_antibody_version_mutations_version_id'), 'antibody_version_mutations', ['version_id'], unique=False)
    op.create_table('antibody_experiments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('version_id', sa.String(length=36), nullable=False),
    sa.Column('sample_batch_id', sa.String(length=36), nullable=True),
    sa.Column('title', sa.String(length=160), nullable=False),
    sa.Column('experiment_type', sa.String(length=32), nullable=False),
    sa.Column('experiment_date', sa.Date(), nullable=True),
    sa.Column('operator_id', sa.String(length=36), nullable=True),
    sa.Column('conditions_json', sa.JSON(), nullable=True),
    sa.Column('result_summary', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['operator_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['antibody_projects.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['sample_batch_id'], ['antibody_sample_batches.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['version_id'], ['antibody_versions.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_antibody_experiments_experiment_type'), 'antibody_experiments', ['experiment_type'], unique=False)
    op.create_index(op.f('ix_antibody_experiments_project_id'), 'antibody_experiments', ['project_id'], unique=False)
    op.create_index(op.f('ix_antibody_experiments_version_id'), 'antibody_experiments', ['version_id'], unique=False)
    op.create_index('ix_antibody_experiments_version_type', 'antibody_experiments', ['version_id', 'experiment_type'], unique=False)
    op.create_table('antibody_experiment_measurements',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('experiment_id', sa.String(length=36), nullable=False),
    sa.Column('metric_name', sa.String(length=64), nullable=False),
    sa.Column('value_numeric', sa.Float(), nullable=True),
    sa.Column('value_text', sa.String(length=255), nullable=True),
    sa.Column('unit', sa.String(length=32), nullable=True),
    sa.Column('qualifier', sa.String(length=16), nullable=True),
    sa.Column('replicate', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('value_numeric IS NOT NULL OR value_text IS NOT NULL', name='ck_antibody_measurement_has_value'),
    sa.ForeignKeyConstraint(['experiment_id'], ['antibody_experiments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_antibody_experiment_measurements_experiment_id'), 'antibody_experiment_measurements', ['experiment_id'], unique=False)
    op.create_index('ix_antibody_measurements_experiment_metric', 'antibody_experiment_measurements', ['experiment_id', 'metric_name'], unique=False)
    op.create_table('antibody_project_artifacts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('version_id', sa.String(length=36), nullable=True),
    sa.Column('sample_batch_id', sa.String(length=36), nullable=True),
    sa.Column('experiment_id', sa.String(length=36), nullable=True),
    sa.Column('job_link_id', sa.String(length=36), nullable=True),
    sa.Column('category', sa.String(length=32), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('storage_path', sa.String(length=512), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('mime_type', sa.String(length=128), nullable=True),
    sa.Column('uploaded_by', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['experiment_id'], ['antibody_experiments.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['job_link_id'], ['antibody_project_job_links.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['project_id'], ['antibody_projects.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['sample_batch_id'], ['antibody_sample_batches.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['version_id'], ['antibody_versions.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'storage_path', name='uq_antibody_artifact_path')
    )
    op.create_index('ix_antibody_artifacts_project_category', 'antibody_project_artifacts', ['project_id', 'category'], unique=False)
    op.create_index(op.f('ix_antibody_project_artifacts_project_id'), 'antibody_project_artifacts', ['project_id'], unique=False)
    op.create_index(op.f('ix_antibody_project_artifacts_sha256'), 'antibody_project_artifacts', ['sha256'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_antibody_project_artifacts_sha256'), table_name='antibody_project_artifacts')
    op.drop_index(op.f('ix_antibody_project_artifacts_project_id'), table_name='antibody_project_artifacts')
    op.drop_index('ix_antibody_artifacts_project_category', table_name='antibody_project_artifacts')
    op.drop_table('antibody_project_artifacts')
    op.drop_index('ix_antibody_measurements_experiment_metric', table_name='antibody_experiment_measurements')
    op.drop_index(op.f('ix_antibody_experiment_measurements_experiment_id'), table_name='antibody_experiment_measurements')
    op.drop_table('antibody_experiment_measurements')
    op.drop_index('ix_antibody_experiments_version_type', table_name='antibody_experiments')
    op.drop_index(op.f('ix_antibody_experiments_version_id'), table_name='antibody_experiments')
    op.drop_index(op.f('ix_antibody_experiments_project_id'), table_name='antibody_experiments')
    op.drop_index(op.f('ix_antibody_experiments_experiment_type'), table_name='antibody_experiments')
    op.drop_table('antibody_experiments')
    op.drop_index(op.f('ix_antibody_version_mutations_version_id'), table_name='antibody_version_mutations')
    op.drop_index('ix_antibody_mutations_version_chain', table_name='antibody_version_mutations')
    op.drop_table('antibody_version_mutations')
    op.drop_index(op.f('ix_antibody_version_chains_version_id'), table_name='antibody_version_chains')
    op.drop_index(op.f('ix_antibody_version_chains_sequence_hash'), table_name='antibody_version_chains')
    op.drop_table('antibody_version_chains')
    op.drop_index(op.f('ix_antibody_sample_batches_version_id'), table_name='antibody_sample_batches')
    op.drop_table('antibody_sample_batches')
    op.drop_index(op.f('ix_antibody_project_job_links_version_id'), table_name='antibody_project_job_links')
    op.drop_index(op.f('ix_antibody_project_job_links_project_id'), table_name='antibody_project_job_links')
    op.drop_index(op.f('ix_antibody_project_job_links_job_id'), table_name='antibody_project_job_links')
    op.drop_table('antibody_project_job_links')
    op.drop_index(op.f('ix_antibody_versions_status'), table_name='antibody_versions')
    op.drop_index(op.f('ix_antibody_versions_sequence_hash'), table_name='antibody_versions')
    op.drop_index('ix_antibody_versions_candidate_status', table_name='antibody_versions')
    op.drop_index(op.f('ix_antibody_versions_candidate_id'), table_name='antibody_versions')
    op.drop_table('antibody_versions')
    op.drop_index(op.f('ix_antibody_project_members_user_id'), table_name='antibody_project_members')
    op.drop_index(op.f('ix_antibody_project_members_project_id'), table_name='antibody_project_members')
    op.drop_table('antibody_project_members')
    op.drop_index(op.f('ix_antibody_candidates_status'), table_name='antibody_candidates')
    op.drop_index('ix_antibody_candidates_project_status', table_name='antibody_candidates')
    op.drop_index(op.f('ix_antibody_candidates_project_id'), table_name='antibody_candidates')
    op.drop_table('antibody_candidates')
    op.drop_index('ix_antibody_audit_project_created', table_name='antibody_audit_events')
    op.drop_index(op.f('ix_antibody_audit_events_request_id'), table_name='antibody_audit_events')
    op.drop_index(op.f('ix_antibody_audit_events_project_id'), table_name='antibody_audit_events')
    op.drop_index('ix_antibody_audit_entity', table_name='antibody_audit_events')
    op.drop_table('antibody_audit_events')
    op.drop_index(op.f('ix_antibody_projects_target_name'), table_name='antibody_projects')
    op.drop_index(op.f('ix_antibody_projects_status'), table_name='antibody_projects')
    op.drop_index('ix_antibody_projects_owner_status', table_name='antibody_projects')
    op.drop_index(op.f('ix_antibody_projects_owner_id'), table_name='antibody_projects')
    op.drop_table('antibody_projects')
    # ### end Alembic commands ###
